#pragma once

#include <QDialog>
#include <QFormLayout>
#include <qtablewidget.h>
#include <qpushbutton.h>
#include <QHeaderView>
#include <qmessagebox.h>
#include <QTextEdit>
#include <QString>
#include <QFileDialog>
#include <fstream>

#include "ui_MoreWindow.h"
#include "Components.h"
#include "TestWindow.h"

#define START_MOREWINDOW_WIDTH			900
#define START_MOREWINDOW_HEIGHT			250
#define START_MOREWINDOW_SIZE			START_MOREWINDOW_WIDTH,START_MOREWINDOW_HEIGHT

#define BUTTON_SIZE						100,40

#define PADDING_MAINWIDGET				10

// BEGIN | OUT
#define OUTALL_ROW_PAD_TABLE							0
#define OUTALL_COLUMN_PAD_TABLE							0
#define OUTALL_CELL_PAD_TABLE							OUTALL_ROW_PAD_TABLE,OUTALL_COLUMN_PAD_TABLE
#define OUTALL_ROW_PIN_TABLE							0
#define OUTALL_COLUMN_PIN_TABLE							1
#define OUTALL_CELL_PIN_TABLE							OUTALL_ROW_TYPE_TABLE,OUTALL_COLUMN_PIN_TABLE
#define OUTALL_ROW_DIRECTION_TABLE						0
#define OUTALL_COLUMN_DIRECTION_TABLE					2
#define OUTALL_CELL_DIRECTION_TABLE						OUTALL_ROW_DIRECTION_TABLE,OUTALL_COLUMN_DIRECTION_TABLE
#define OUTALL_ROW_TYPE_TABLE							0
#define OUTALL_COLUMN_TYPE_TABLE						3
#define OUTALL_CELL_TYPE_TABLE							OUTALL_ROW_TYPE_TABLE,OUTALL_COLUMN_TYPE_TABLE
#define OUTALL_ROW_NAME_TABLE							0
#define OUTALL_COLUMN_NAME_TABLE						4
#define OUTALL_CELL_NAME_TABLE							OUTALL_ROW_NAME_TABLE,OUTALL_COLUMN_NAME_TABLE
#define OUTALL_ROW_NAME_MEASURED_TABLE					0
#define OUTALL_COLUMN_NAME_MEASURED_TABLE				5
#define OUTALL_ROW_MEASURED_VALUE_TABLE					1
#define OUTALL_COLUMN_MEASURED_VALUE_TABLE				5
#define OUTALL_ROW_MEASURED_VALUE_U_TABLE				3
#define OUTALL_COLUMN_MEASURED_VALUE_U_TABLE			5
#define OUTALL_ROW_MEASURED_VALUE_I_TABLE				3
#define OUTALL_COLUMN_MEASURED_VALUE_I_TABLE			6
#define OUTALL_ROW_TRESHHOLDERS_TABLE					1
#define OUTALL_COLUMN_TRESHHOLDERS_TABLE				7
#define OUTALL_ROW_TRESHHOLDERS_U_TABLE					2
#define OUTALL_COLUMN_TRESHHOLDERS_U_TABLE				7
#define OUTALL_ROW_TRESHHOLDERS_I_TABLE					2
#define OUTALL_COLUMN_TRESHHOLDERS_I_TABLE				9
#define OUTALL_ROW_TRESHHOLDERS_U_MIN_TABLE				3
#define OUTALL_COLUMN_TRESHHOLDERS_U_MIN_TABLE			7
#define OUTALL_ROW_TRESHHOLDERS_U_MAX_TABLE				3
#define OUTALL_COLUMN_TRESHHOLDERS_U_MAX_TABLE			8
#define OUTALL_ROW_TRESHHOLDERS_I_MIN_TABLE				3
#define OUTALL_COLUMN_TRESHHOLDERS_I_MIN_TABLE			9
#define OUTALL_ROW_TRESHHOLDERS_I_MAX_TABLE				3
#define OUTALL_COLUMN_TRESHHOLDERS_I_MAX_TABLE			10
#define OUTALL_ROW_COMMENT_TABLE						0
#define OUTALL_COLUMN_COMMENT_TABLE						5
#define OUTALL_CELL_COMMENT_TABLE						OUTALL_ROW_COMMENT_TABLE,OUTALL_COLUMN_COMMENT_TABLE

#define OUTALL_CEll_VALUE_PAD_TABLE						4,0
#define OUTALL_CELL_VALUE_PIN_TABLE						4,1
#define OUTALL_CELL_VALUE_DIRECTION_TABLE				4,2
#define OUTALL_CELL_VALUE_TYPE_TABLE					4,3
#define OUTALL_CELL_VALUE_NAME_TABLE					4,4
#define OUTALL_ROW_VALUE_MEASURED_VALUE_U_TABLE			4
#define OUTALL_COLUMN_VALUE_MEASURED_VALUE_U_TABLE		5
#define OUTALL_CELL_VALUE_MEASURED_VALUE_U_TABLE		OUTALL_ROW_VALUE_MEASURED_VALUE_U_TABLE,OUTALL_COLUMN_VALUE_MEASURED_VALUE_U_TABLE
#define OUTALL_ROW_VALUE_MEASURED_VALUE_I_TABLE			4
#define OUTALL_COLUMN_VALUE_MEASURED_VALUE_I_TABLE		6
#define OUTALL_CELL_VALUE_MEASURED_VALUE_I_TABLE		OUTALL_ROW_VALUE_MEASURED_VALUE_I_TABLE,OUTALL_COLUMN_VALUE_MEASURED_VALUE_I_TABLE
#define OUTALL_ROW_VALUE_TRESHHOLDERS_U_MIN_TABLE		4
#define OUTALL_COLUMN_VALUE_TRESHHOLDERS_U_MIN_TABLE	7
#define OUTALL_CELL_VALUE_TRESHHOLDERS_U_MIN_TABLE		OUTALL_ROW_VALUE_TRESHHOLDERS_U_MIN_TABLE,OUTALL_COLUMN_VALUE_TRESHHOLDERS_U_MIN_TABLE
#define OUTALL_ROW_VALUE_TRESHHOLDERS_U_MAX_TABLE		4
#define OUTALL_COLUMN_VALUE_TRESHHOLDERS_U_MAX_TABLE	8
#define OUTALL_CELL_VALUE_TRESHHOLDERS_U_MAX_TABLE		OUTALL_ROW_VALUE_TRESHHOLDERS_U_MAX_TABLE,OUTALL_COLUMN_VALUE_TRESHHOLDERS_U_MAX_TABLE
#define OUTALL_ROW_VALUE_TRESHHOLDERS_I_MIN_TABLE		4
#define OUTALL_COLUMN_VALUE_TRESHHOLDERS_I_MIN_TABL		9
#define OUTALL_CELL_VALUE_TRESHHOLDERS_I_MIN_TABLE		OUTALL_ROW_VALUE_TRESHHOLDERS_I_MIN_TABLE,OUTALL_COLUMN_VALUE_TRESHHOLDERS_I_MIN_TABLE
#define OUTALL_ROW_VALUE_TRESHHOLDERS_I_MAX_TABLE		4
#define OUTALL_COLUMN_VALUE_TRESHHOLDERS_I_MAX_TABLE	10
#define OUTALL_CELL_VALUE_TRESHHOLDERS_I_MAX_TABLE		OUTALL_ROW_VALUE_TRESHHOLDERS_I_MAX_TABLE,OUTALL_COLUMN_VALUE_TRESHHOLDERS_I_MAX_TABLE
#define OUTALL_ROW_VALUE_COMMENT_TABLE					4
#define OUTALL_COLUMN_VALUE_COMMENT_TABLE				5
#define OUTALL_CELL_VALUE_COMMENT_TABLE					OUTALL_ROW_VALUE_COMMENT_TABLE,OUTALL_COLUMN_VALUE_COMMENT_TABLE

#define OUTALL_WIDTH_BLOCK_TRESHHOLDERS					6
#define OUTALL_OFFSET_BLOCK_TRESHHOLDERS(num)			num * OUTALL_WIDTH_BLOCK_TRESHHOLDERS
// END | OUT
// BEGIN | IN ANALOG
#define INANALOG_ROW_PAD_TABLE							0
#define INANALOG_COLUMN_PAD_TABLE						0
#define INANALOG_CELL_PAD_TABLE							INANALOG_ROW_PAD_TABLE,INANALOG_COLUMN_PAD_TABLE
#define INANALOG_ROW_PIN_TABLE							0
#define INANALOG_COLUMN_PIN_TABLE						1
#define INANALOG_CELL_PIN_TABLE							INANALOG_ROW_TYPE_TABLE,INANALOG_COLUMN_PIN_TABLE
#define INANALOG_ROW_TYPE_TABLE							0
#define INANALOG_COLUMN_TYPE_TABLE						2
#define INANALOG_CELL_TYPE_TABLE						INANALOG_ROW_TYPE_TABLE,INANALOG_COLUMN_TYPE_TABLE
#define INANALOG_ROW_NAME_TABLE							0
#define INANALOG_COLUMN_NAME_TABLE						3
#define INANALOG_CELL_NAME_TABLE						INANALOG_ROW_NAME_TABLE,INANALOG_COLUMN_NAME_TABLE
#define INANALOG_ROW_NAME_MEASURED_TABLE				0
#define INANALOG_COLUMN_NAME_MEASURED_TABLE				4
#define INANALOG_ROW_MEASURED_VALUE_TABLE				1
#define INANALOG_COLUMN_MEASURED_VALUE_TABLE			4
#define INANALOG_ROW_TRESHHOLDERS_TABLE					1
#define INANALOG_COLUMN_TRESHHOLDERS_TABLE				5
#define INANALOG_ROW_TRESHHOLDERS_MIN_TABLE				2
#define INANALOG_COLUMN_TRESHHOLDERS_MIN_TABLE			5
#define INANALOG_ROW_TRESHHOLDERS_MAX_TABLE				2
#define INANALOG_COLUMN_TRESHHOLDERS_MAX_TABLE			6
#define INANALOG_ROW_COMMENT_TABLE						4
#define INANALOG_COLUMN_COMMENT_TABLE					4
#define INANALOG_CELL_COMMENT_TABLE						INANALOG_ROW_COMMENT_TABLE,INANALOG_COLUMN_COMMENT_TABLE

#define INANALOG_CEll_VALUE_PAD_TABLE					3,0
#define INANALOG_CELL_VALUE_PIN_TABLE					3,1
#define INANALOG_CELL_VALUE_TYPE_TABLE					3,2
#define INANALOG_CELL_VALUE_NAME_TABLE					3,3
#define INANALOG_CELL_VALUE_MEASURED_VALUE_TABLE		3,4
#define INANALOG_CELL_VALUE_TRESHHOLDERS_MIN_TABLE		3,6
#define INANALOG_CELL_VALUE_TRESHHOLDERS_MAX_TABLE		3,7
#define INANALOG_ROW_VALUE_COMMENT_TABLE				3
#define INANALOG_COLUMN_VALUE_COMMENT_TABLE				4
#define INANALOG_CELL_VALUE_COMMENT_TABLE				INANALOG_ROW_VALUE_COMMENT_TABLE,INANALOG_COLUMN_VALUE_COMMENT_TABLE

#define INANALOG_WIDTH_BLOCK_TRESHHOLDERS				3
#define INANALOG_OFFSET_BLOCK_TRESHHOLDERS(num)			num * INANALOG_WIDTH_BLOCK_TRESHHOLDERS
// END | IN ANALOG
// BEGIN | IN DIG
#define INDIG_ROW_PAD_TABLE							0
#define INDIG_COLUMN_PAD_TABLE						0
#define INDIG_CELL_PAD_TABLE						INDIG_ROW_PAD_TABLE,INDIG_COLUMN_PAD_TABLE
#define INDIG_ROW_PIN_TABLE							0
#define INDIG_COLUMN_PIN_TABLE						1
#define INDIG_CELL_PIN_TABLE						INDIG_ROW_TYPE_TABLE,INDIG_COLUMN_PIN_TABLE
#define INDIG_ROW_TYPE_TABLE						0
#define INDIG_COLUMN_TYPE_TABLE						2
#define INDIG_CELL_TYPE_TABLE						INDIG_ROW_TYPE_TABLE,INDIG_COLUMN_TYPE_TABLE
#define INDIG_ROW_NAME_TABLE						0
#define INDIG_COLUMN_NAME_TABLE						3
#define INDIG_CELL_NAME_TABLE						INDIG_ROW_NAME_TABLE,INDIG_COLUMN_NAME_TABLE
#define INDIG_ROW_FIRST_MEASURED_TABLE				0
#define INDIG_COLUMN_FIRST_MEASURED_TABLE			4
#define INDIG_CELL_FIRST_MEASURED_TABLE				INDIG_ROW_FIRST_MEASURED_TABLE,INDIG_COLUMN_FIRST_MEASURED_TABLE
#define INDIG_ROW_SECOND_MEASURED_TABLE				0
#define INDIG_COLUMN_SECOND_MEASURED_TABLE			5
#define INDIG_CELL_SECOND_MEASURED_TABLE			INDIG_ROW_SECOND_MEASURED_TABLE,INDIG_COLUMN_SECOND_MEASURED_TABLE
#define INDIG_ROW_COMMENT_TABLE						0
#define INDIG_COLUMN_COMMENT_TABLE					6
#define INDIG_CELL_COMMENT_TABLE					INDIG_ROW_COMMENT_TABLE,INDIG_COLUMN_COMMENT_TABLE

#define INDIG_CEll_VALUE_PAD_TABLE					1,0
#define INDIG_CELL_VALUE_PIN_TABLE					1,1
#define INDIG_CELL_VALUE_TYPE_TABLE					1,2
#define INDIG_CELL_VALUE_NAME_TABLE					1,3
#define INDIG_ROW_VALUE_COMMENT_TABLE				1
#define INDIG_COLUMN_VALUE_COMMENT_TABLE			6
#define INDIG_CELL_VALUE_COMMENT_TABLE				INDIG_ROW_VALUE_COMMENT_TABLE,INDIG_COLUMN_VALUE_COMMENT_TABLE
// END | IN DIG

#define BASE_COLUMN_COUNT			6
#define BASE_ROW_COUNT				2

#define MEASUREMENT_COLUMN_POSITION	5
#define MEASURED_OFFSET_SEXTUPLE	6
#define MEASURED_OFFSET_TRIPPLE		3

#define ROW_OFFSET_DOUBLE			2
#define ROW_OFFSET_TRIPPLE			3

#define SPAN_NONE					1, 1

#define SPAN_VERTICAL_DOUBLE		2, 1
#define SPAN_VERTICAL_TRIPPLE		3, 1
#define SPAN_VERTICAL_QUADRUPLE		4, 1

#define SPAN_HORIZONTAL_DOUBLE		1, 2
#define SPAN_HORIZONTAL_TRIPPLE		1, 3
#define SPAN_HORIZONTAL_QUADRUPLE	1, 4
#define SPAN_HORIZONTAL_SEXTUPLE	1, 6

#define SPAN_SQUAD_DOUBLE			2, 2

#define IND_ROW_BASE_SIGN					0
#define IND_ROW_BASE_VALUE					1
#define IND_ROW_FILLED_SIGN					IND_ROW_BASE_SIGN
#define IND_ROW_FILLED_VALUE_HALL			3
#define IND_ROW_FILLED_VALUE				4

#define IND_ROW_BASE_SIGN_CONNECTOR			IND_ROW_BASE_SIGN
#define IND_ROW_BASE_SIGN_PIN				IND_ROW_BASE_SIGN
#define IND_ROW_BASE_SIGN_DIRECTION			IND_ROW_BASE_SIGN
#define IND_ROW_BASE_SIGN_TYPE				IND_ROW_BASE_SIGN
#define IND_ROW_BASE_SIGN_NAME				IND_ROW_BASE_SIGN
#define IND_ROW_BASE_SIGN_COMPONENT			IND_ROW_BASE_SIGN
#define IND_ROW_BASE_SIGN_COMMENT			IND_ROW_BASE_SIGN

#define IND_ROW_BASE_VALUE_CONNECTOR		IND_ROW_BASE_VALUE
#define IND_ROW_BASE_VALUE_PIN				IND_ROW_BASE_VALUE
#define IND_ROW_BASE_VALUE_DIRECTION		IND_ROW_BASE_VALUE
#define IND_ROW_BASE_VALUE_TYPE				IND_ROW_BASE_VALUE
#define IND_ROW_BASE_VALUE_NAME				IND_ROW_BASE_VALUE
#define IND_ROW_BASE_VALUE_COMPONENT		IND_ROW_BASE_VALUE
#define IND_ROW_BASE_VALUE_COMMENT			IND_ROW_BASE_VALUE

#define IND_ROW_FILLED_SIGN_CONNECTOR		IND_ROW_FILLED_SIGN
#define IND_ROW_FILLED_SIGN_PIN				IND_ROW_FILLED_SIGN
#define IND_ROW_FILLED_SIGN_DIRECTION		IND_ROW_FILLED_SIGN
#define IND_ROW_FILLED_SIGN_TYPE			IND_ROW_FILLED_SIGN
#define IND_ROW_FILLED_SIGN_NAME			IND_ROW_FILLED_SIGN
#define IND_ROW_FILLED_SIGN_COMPONENT		IND_ROW_FILLED_SIGN
#define IND_ROW_FILLED_SIGN_COMMENT			IND_ROW_FILLED_SIGN

#define IND_ROW_FILLED_VALUE_CONNECTOR		IND_ROW_FILLED_VALUE
#define IND_ROW_FILLED_VALUE_PIN			IND_ROW_FILLED_VALUE
#define IND_ROW_FILLED_VALUE_DIRECTION		IND_ROW_FILLED_VALUE
#define IND_ROW_FILLED_VALUE_TYPE			IND_ROW_FILLED_VALUE
#define IND_ROW_FILLED_VALUE_NAME			IND_ROW_FILLED_VALUE
#define IND_ROW_FILLED_VALUE_COMPONENT		IND_ROW_FILLED_VALUE
#define IND_ROW_FILLED_VALUE_COMMENT		IND_ROW_FILLED_VALUE

#define OFFSET_NULL							0
#define OFFSET_DIGITAL						12
#define OFFSET_PWM							12
#define OFFSET_VNH							18
#define OFFSET_ANALOG						6

#define IND_COLUMN_BASE_CONNECTOR			0
#define IND_COLUMN_BASE_PIN					1
#define IND_COLUMN_BASE_DIRECTION			2
#define IND_COLUMN_BASE_TYPE				3
#define IND_COLUMN_BASE_NAME				4
#define IND_COLUMN_BASE_COMMENT				5

#define IND_COLUMN_FILLED_CONNECTOR			IND_COLUMN_BASE_CONNECTOR
#define IND_COLUMN_FILLED_PIN				IND_COLUMN_BASE_PIN
#define IND_COLUMN_FILLED_DIRECTION			IND_COLUMN_BASE_DIRECTION
#define IND_COLUMN_FILLED_TYPE				IND_COLUMN_BASE_TYPE
#define IND_COLUMN_FILLED_NAME				IND_COLUMN_BASE_NAME
#define IND_COLUMN_FILLED_COMMENT(offset)	IND_COLUMN_BASE_COMMENT + offset

#define CELL_SIGN_BASE_CONNECTOR			IND_ROW_BASE_SIGN_CONNECTOR,	IND_COLUMN_BASE_CONNECTOR
#define CELL_SIGN_BASE_PIN					IND_ROW_BASE_SIGN_PIN,			IND_COLUMN_BASE_PIN
#define CELL_SIGN_BASE_DIRECTION			IND_ROW_BASE_SIGN_DIRECTION,	IND_COLUMN_BASE_DIRECTION
#define CELL_SIGN_BASE_TYPE					IND_ROW_BASE_SIGN_TYPE,			IND_COLUMN_BASE_TYPE
#define CELL_SIGN_BASE_NAME					IND_ROW_BASE_SIGN_NAME,			IND_COLUMN_BASE_NAME
#define CELL_SIGN_BASE_COMMENT				IND_ROW_BASE_SIGN_COMMENT,		IND_COLUMN_BASE_COMMENT

#define CELL_SIGN_FILLED_CONNECTOR			IND_ROW_FILLED_SIGN_CONNECTOR,	IND_COLUMN_FILLED_CONNECTOR
#define CELL_SIGN_FILLED_PIN				IND_ROW_FILLED_SIGN_PIN,		IND_COLUMN_FILLED_PIN
#define CELL_SIGN_FILLED_DIRECTION			IND_ROW_FILLED_SIGN_DIRECTION,	IND_COLUMN_FILLED_DIRECTION
#define CELL_SIGN_FILLED_TYPE				IND_ROW_FILLED_SIGN_TYPE,		IND_COLUMN_FILLED_TYPE
#define CELL_SIGN_FILLED_NAME				IND_ROW_FILLED_SIGN_NAME,		IND_COLUMN_FILLED_NAME
#define CELL_SIGN_FILLED_COMMENT(offset)	IND_ROW_FILLED_SIGN_COMMENT,	IND_COLUMN_FILLED_COMMENT(offset)

#define CELL_VALUE_BASE_CONNECTOR			IND_ROW_BASE_VALUE_CONNECTOR,	IND_COLUMN_BASE_CONNECTOR
#define CELL_VALUE_BASE_PIN					IND_ROW_BASE_VALUE_PIN,			IND_COLUMN_BASE_PIN
#define CELL_VALUE_BASE_DIRECTION			IND_ROW_BASE_VALUE_DIRECTION,	IND_COLUMN_BASE_DIRECTION
#define CELL_VALUE_BASE_TYPE				IND_ROW_BASE_VALUE_TYPE,		IND_COLUMN_BASE_TYPE
#define CELL_VALUE_BASE_NAME				IND_ROW_BASE_VALUE_NAME,		IND_COLUMN_BASE_NAME
#define CELL_VALUE_BASE_COMMENT				IND_ROW_BASE_VALUE_COMMENT,		IND_COLUMN_BASE_COMMENT

#define CELL_VALUE_FILLED_CONNECTOR			IND_ROW_FILLED_VALUE_CONNECTOR,	IND_COLUMN_FILLED_CONNECTOR
#define CELL_VALUE_FILLED_PIN				IND_ROW_FILLED_VALUE_PIN,		IND_COLUMN_FILLED_PIN
#define CELL_VALUE_FILLED_DIRECTION			IND_ROW_FILLED_VALUE_DIRECTION,	IND_COLUMN_FILLED_DIRECTION
#define CELL_VALUE_FILLED_TYPE				IND_ROW_FILLED_VALUE_TYPE,		IND_COLUMN_FILLED_TYPE
#define CELL_VALUE_FILLED_NAME				IND_ROW_FILLED_VALUE_NAME,		IND_COLUMN_FILLED_NAME
#define CELL_VALUE_FILLED_COMMENT(offset)	IND_ROW_FILLED_VALUE_COMMENT,	IND_COLUMN_FILLED_COMMENT(offset)

#define IND_ROW_SIGN_MEASURED				0
#define IND_ROW_SIGN_MEASURED_VALUES		1
#define IND_ROW_SIGN_MEASURED_CURRENT		3
#define IND_ROW_SIGN_MEASURED_VOLTAGE		3
#define IND_ROW_SIGN_THRESHOLDS				1
#define IND_ROW_SIGN_CURRENT				2
#define IND_ROW_SIGN_VOLTAGE				2
#define IND_ROW_SIGN_MIN_CURRENT			3
#define IND_ROW_SIGN_MAX_CURRENT			3
#define IND_ROW_SIGN_MIN_VOLTAGE			3
#define IND_ROW_SIGN_MAX_VOLTAGE			3

#define IND_COLUMN_SIGN_MEASURED			5
#define IND_COLUMN_SIGN_MEASURED_VALUES		5
#define IND_COLUMN_SIGN_MEASURED_CURRENT	5
#define IND_COLUMN_SIGN_MEASURED_VOLTAGE	6
#define IND_COLUMN_SIGN_THRESHOLDS			7
#define IND_COLUMN_SIGN_CURRENT				7
#define IND_COLUMN_SIGN_VOLTAGE				9
#define IND_COLUMN_SIGN_MIN_CURRENT			7
#define IND_COLUMN_SIGN_MAX_CURRENT			8
#define IND_COLUMN_SIGN_MIN_VOLTAGE			9
#define IND_COLUMN_SIGN_MAX_VOLTAGE			10

#define CELL_SIGN_MEASURED					IND_ROW_SIGN_MEASURED,			IND_COLUMN_SIGN_MEASURED
#define CELL_SIGN_MEASURED_VALUES			IND_ROW_SIGN_MEASURED_VALUES,	IND_COLUMN_SIGN_MEASURED_VALUES
#define CELL_SIGN_MEASURED_CURRENT			IND_ROW_SIGN_MEASURED_CURRENT,	IND_COLUMN_SIGN_MEASURED_CURRENT
#define CELL_SIGN_MEASURED_VOLTAGE			IND_ROW_SIGN_MEASURED_VOLTAGE,	IND_COLUMN_SIGN_MEASURED_VOLTAGE
#define CELL_SIGN_THRESHOLDS				IND_ROW_SIGN_THRESHOLDS,		IND_COLUMN_SIGN_THRESHOLDS
#define CELL_SIGN_THRESHOLDS_CURRENT		IND_ROW_SIGN_CURRENT,			IND_COLUMN_SIGN_CURRENT
#define CELL_SIGN_THRESHOLDS_VOLTAGE		IND_ROW_SIGN_VOLTAGE,			IND_COLUMN_SIGN_VOLTAGE
#define CELL_SIGN_MIN_CURRENT				IND_ROW_SIGN_MIN_CURRENT,		IND_COLUMN_SIGN_MIN_CURRENT
#define CELL_SIGN_MAX_CURRENT				IND_ROW_SIGN_MAX_CURRENT,		IND_COLUMN_SIGN_MAX_CURRENT
#define CELL_SING_MIN_VOLTAGE				IND_ROW_SIGN_MIN_VOLTAGE,		IND_COLUMN_SIGN_MIN_VOLTAGE
#define CELL_SING_MAX_VOLTAGE				IND_ROW_SIGN_MAX_VOLTAGE,		IND_COLUMN_SIGN_MAX_VOLTAGE

#define IND_ROW_VALUES						4

#define CELL_VALUES_MEASURED_CURRENT		IND_ROW_VALUES,	IND_COLUMN_SIGN_MEASURED_CURRENT
#define CELL_VALUES_MEASURED_VOLTAGE		IND_ROW_VALUES,	IND_COLUMN_SIGN_MEASURED_VOLTAGE
#define CELL_VALUES_MIN_CURRENT				IND_ROW_VALUES,	IND_COLUMN_SIGN_MIN_CURRENT
#define CELL_VALUES_MAX_CURRENT				IND_ROW_VALUES,	IND_COLUMN_SIGN_MAX_CURRENT
#define CELL_VALUES_MIN_VOLTAGE				IND_ROW_VALUES,	IND_COLUMN_SIGN_MIN_VOLTAGE
#define CELL_VALUES_MAX_VOLTAGE				IND_ROW_VALUES,	IND_COLUMN_SIGN_MAX_VOLTAGE

#define IND_COLUMN_SIGN_MEASURED_HALL
#define IND_COLUMN_SIGN_MEASURED_VALUES_HALL
#define IND_COLUMN_SIGN_MEASURED_CURRENT_HALL
#define IND_COLUMN_SIGN_MEASURED_VOLTAGE_HALL

#define WINDOW_HEIGHT			300
#define EMPTY_WINDOW_WIDTH		600
#define WINDOW_MEASURED_WIDTH	300

class TestTableRowProperties;
class MoreWindow : public QDialog
{
	Q_OBJECT

public:
	MoreWindow(TestTableRowProperties* row, int startWidth, int startHeight);
	~MoreWindow();

	enum TypeMoreWindow
	{
		MoreWindowOutDig,
		MoreWindowOutPwm,
		MoreWindowOutVnh,
		MoreWindowInDig,
		MoreWindowInAnalog,
		MoreWindowBuses,
		MoreWindowError
	};

protected:
	QTableWidget* mainTableWidget;
	QTextEdit* commentTextEdit;
	QPushButton* saveChangesButton;
	QFont* font;

	TestTableRowProperties* row;
	int coutThresholds;
	bool isAllInit;

	void prepareItem(int row, int column, int rowSpan, int columnSpan);
	void resetLanguage(int offset);
	void resetBlockLanguage(int measuredNum);
	void setValues();

private:
	void initBaseUi();
	void fillBaseTable();

	void resizeEvent(QResizeEvent* event) { mainWidget->resize(geometry().width() - (PADDING_MAINWIDGET * 2), geometry().height() - PADDING_MAINWIDGET); };

	//void resaveFile(QString fileName, Cable newCable);

	QWidget* mainWidget;
	QVBoxLayout* mainVLayout;
	QHBoxLayout* bottomHLayout;
	QSpacerItem* bottomSpacer;
	QPushButton* startTestButton;

public slots:
	void on_mainTableWidget_cellChanged(int row, int column);
	void on_commentTextEdit_textChanged();
	void on_saveChangesButton_clicked();
	void on_startTestButton_clicked();
};


//class MoreWindowOut : public MoreWindow
//{
//public:
//	MoreWindowOut(TestTableRowProperties* row, int startWidth, int startHeight) : MoreWindow(row, startWidth, startHeight) {};
//	//public slots:
//		//void on_mainTableWidget_cellChanged(int row, int column);
//protected:
//	void initUiTableOut();
//};

#define SIZE_MOREWINDOW_OUT			1200,	300
#define SIZE_MOREWINDOW_OUT_VNH		1500,	300

class MoreWindowOut : public MoreWindow
{
public:
	MoreWindowOut(TestTableRowProperties* row);

private:
	TestTableRowProperties* row;

	void generateSigns();
	void generateThresholds(Measureds measured, Thresholds threshold);
};

class MoreWindowOutDig final : public MoreWindowOut
{
public:
	MoreWindowOutDig(TestTableRowProperties* row);
};

class MoreWindowOutPwm final : public MoreWindowOut
{
public:
	MoreWindowOutPwm(TestTableRowProperties* row);
};

class MoreWindowOutVnh final : public MoreWindowOut
{
public:
	MoreWindowOutVnh(TestTableRowProperties* row);
};

class MoreWindowIn : public MoreWindow
{
public:
	MoreWindowIn(TestTableRowProperties* row, int startWidth, int startHeight) : MoreWindow(row, startWidth, startHeight) {};
protected:
	void initUiTableIn(TypeMoreWindow typeWindow);
};

#define SIZE_MOREWINDOW_IN_DIG		800,200
class MoreWindowInDig final : public MoreWindowIn
{
public:
	MoreWindowInDig(TestTableRowProperties* row);
};

#define SIZE_MOREWINDOW_IN_ANALOG		1200,250
class MoreWindowInAnalog final : public MoreWindowIn
{
public:
	MoreWindowInAnalog(TestTableRowProperties* row);
};
